#When is the finally block executed?
'''
->The finally block in a try-except-finally statement in Python is executed regardless of whether an exception is raised or not.
->It ensures that a particular block of code is always executed.
->The finally block is useful for tasks that must be performed, 
    such as closing files or network connections, releasing resources, or cleaning up, regardless of the outcome of the code in the try block.

'''